- Frontend/.gitignore
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/App.js
- Frontend/src/components/Header.js
- Frontend/src/pages/member/Login.js
- Frontend/src/pages/mystudy/CreatePost.js
- Frontend/src/routes/Home.js
- Frontend/src/styles/components/Header.css
> '#이슈번호 문제 내용' 과 같은 형식으로 작성해주세요.
* #4 react 구조 정리
> 
<br/>
* 구조가 어떻게 되어있는지 예전에 배웠던 프로젝트로 분석하고, gpt랑 구글링해서 찾았음
<br/>
* src 밑 폴더 구조 
* App.js route 하는 방법 
* <a href="https://internal-city-3b1.notion.site/react-c89b966db54b42f2bc2439d0ff0f7792">리액트 구조 정리</a> → 정리해놨으니 한 번씩 보기 & 모르는 거 있으면 물어보기 
* npm install 할 때 .gitignore 파일에 node_modules 이 있어야 한다. 없으면 커밋 10000개 이상 뜨게 됨 
* pull 받고 npm install OR yarn install 해주기 (react-router-dom 설치함)
> React 기본 구조 작성

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/StudyProjectApplication.java
- Backend/src/main/java/com/example/studyproject/member/Member.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/application.properties
- Backend/src/main/resources/log4j2.xml
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
주입
* https://github.com/seoyeonDev/Su-p/issues/16
> 
<br/>
* mybatis 연동 작업
* Member class 기초 세팅
* Member mapper 생성
* log4j2 설정
<br/>
* mybatis 연동은 기본적으로 두 가지 설정을 해주어야 하고 class 파일과 xml이 맵핑되도록 id 및 mapper 경로를 잘 지정해주어야 한다.
* pom.xml에 mybatis 의존성을 주입해주고, springboot의 main 클래스에 @Mapperscan("최상위 패키지명")을 추가하여 스프링부트의 main 클래스가 실행될 때 Mapper(dao)를 훑도록 설정해준다.
* application.properties에서 사용할 db의 설정에 mybatis.mapper-locations로 쿼리를 작성할 mapper의 경로를 지정해준다.
* 위에 설정해준 경로에 클래스별 SQL mapper(xml)를 생성해주고 맵핑할 mapper의 id와 실행할 쿼리를 작성해준다.
*  Member(vo) 클래스에는  db 컬럼을 맵핑해준다.
* MemberDao(mapper) 클래스에는 @Mapper를 추가하여 스프링부트가 실행될 때 해당 Mapper를 훑도록 해주고, SQL mapper에 지정해 줄 아이디와 리턴 클래스를 작성해준다.
* …
> 20240324 봉선호: mybatis 연동, Member class 기초 세팅, Member mapper 생성, log4j2

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* 이슈번호 없음.. 주석만 추가함
> 
<br/>
* 설명 보충위해 주석 추가
<br/>
* -
> 20240324 봉선호: 주석 추가

- Frontend/src/App.js
- Frontend/src/pages/member/Join.js
- Frontend/src/pages/member/Login.js
- Frontend/src/styles/components/Member.css
* #6 리액트 화면 생성
> 
<br/>
- member 회원가입 화면 생성
- member 로그인 화면 생성
<br/>
* 기본 css 만 적용 (display 만 적용)
* 가입약관 체크박스와 회원가입 버튼 중복 문제 해결 못함
* css 를 어떻게 적용할지 못 정했기 때문에 html 화면만 생성
* css 적용 방법에 따라 div 구조 수정이 필요할 것으로 예상됨
> #6 : member : 회원가입 & 로그인 화면 생성 : 신규

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
> Revert "20240324 봉선호: 주석 추가"

- Backend/src/main/java/com/example/studyproject/member/Member.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/java/com/example/studyproject/util/Sha256.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #26
* #28 
> 
<br/>
* 회원가입: default 설정된 가입일, 실패횟수, 잠금여부 제외한 유저 정보 입력 받아서  db에 저장
* 비밀번호는 SHA-256 알고리즘 적용하여 단방향 암호화 처리(com.example.studyproject.util에서 확인 가능함)
* 로그인: 로그인 시도 3회 이상 시 잠금 기능 기본 설정하여 로그인 기능 추가
<br/>
* merge 없이 새로운 브랜치로 작업하면 이전 브랜치로 작업한 내용을 pull 할 수가 없어서 26브랜치로 28 작업도 함
* 작업 완료 시간과 리뷰어의 리뷰 시간이 맞지 않으면 새로운 브랜치로 작업하기엔 다소 무리 있어보임
* 비밀번호는 복호화 되면 보안에 취약하므로 양방향이 아닌 단방향 모듈로 암호화 처리함
* db에 default 설정되어 있는 가입일 저장되는 형식 수정 필요해보임
* db에서 형식 수정이 안된다면 default 해제하고 java에서 형식 수정해서 db에 저장해야 할 듯 함
* lombok 어노테이션 적용만 되고 실제로 기능 이용이 불가능한 상태임, 확인 필요함!
* get, set 이용 불가해서 임의로 getter, setter, toString, Constructor 설정해놓음
* select로 유저 정보 불러올 때 아이디, 가입일, 이미지, 실패횟수, 잠금여부  null로 불러와짐
* 위에서 …
> 20240331 봉선호: 회원가입, 로그인

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/member/Member.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/application.properties
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #26 
* #28 
> 
<br/>
* postgresql 컬럼명과 vo의 변수명이 일치하지 않아서 일치하지 않은 부분이 null로 뜸
* 일치하게 수정해서 에러 수정
* 로그인 로직 수정
<br/>
* 회원가입 로직
* 로그인 로직
> 20240406 봉선호: 회원가입, 로그인 수정

- Backend/src/main/java/com/example/studyproject/TestController.java
- Frontend/src/routes/Home.js
* #31 
> 
<br/>
* react와 spring 연결하는 코드를 작성했습니다. 
<br/>
* input으로 post 보내는 부분
> react spring 값 보내고 받아오는 코드 작성

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/src/pages/member/Join.js
- Frontend/src/pages/member/Login.js
- Spring 데이터 불러오기 (Get 방식)
* #31 Axios 를 통해 Spring 데이터 불러오기
> 
<br/>
* Axios 를 통해 작업완료. 
<br/>
*
> #31 : member : Axios Test : 신규

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- MemberController 이전 버전 내용 삭제
* 이전 버전 메서드 삭제
> 
<br/>
* 이전 버전 메서드 member/userId 삭제
<br/>
*
> X : 이서연 : member : 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/application.properties
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #37 
> 
<br/>
* 회원가입 시 이미지도 저장되도록 기능 추가
* 멤버 수정: 비밀번호, 닉네임, 이미지 경로 수정
<br/>
* application.properties에 이미지 저장될 경로 추가함
* 클라우드가 아닌 로컬에 저장하므로 각자의 경로로 수정해야할 듯
* MultipartFile, File 이용하여 이미지 저장 및 수정 기능 추가
* 이메일도 수정하나?
> 20240415 SUNHO: 회원가입 이미지 저장 추가 및 멤버 수정 기능 추가

- Backend/src/main/java/com/example/studyproject/group/Group.java
* #42 
> 
<br/>
* pr 분리 후 Group vo 만들기 
<br/>
*
> 20240416 김혜원 : 그룹 vo 만들기

- Backend/src/main/java/com/example/studyproject/group/GroupController.java
- Backend/src/main/java/com/example/studyproject/group/GroupDao.java
- Backend/src/main/java/com/example/studyproject/group/GroupService.java
- Backend/src/main/resources/sqlMapper/group/GroupManage_SQL.xml
* #47 
> 
<br/>
* 코드 작성을 위한 빈 파일이므로 pr 바로 합니다.
<br/>
*
> issue #47 : 선호 : group : dao, service, controller, xml 빈 파일 생성

- Backend/src/main/java/com/example/studyproject/util/Annotation.java
* #76 
> 
<br/>
* 기본 주석양식
<br/>
*
> i #76 : 봉선호 : 주석양식 : 주석양식 작성

- Backend/src/main/java/com/example/studyproject/group/Group.java
- Backend/src/main/java/com/example/studyproject/group/GroupController.java
- Backend/src/main/java/com/example/studyproject/group/GroupDao.java
- Backend/src/main/java/com/example/studyproject/group/GroupService.java
- Backend/src/main/resources/sqlMapper/group/GroupManage_SQL.xml
* #49 
> 
<br/>
* 그룹 추가 기본 코드 및 쿼리 생성
<br/>
* 그룹 컬럼에 그룹장 id가 있는데 로그인 할 때 세션에 로그인한 아이디 저장하고,
* 그룹 추가 컨트롤러에서 세션에 저장되어 있는 아이디 불러와서 vo.set 형식으로 할 것 인지?
* 우선은 가장 기초적인 insert 코드만 생성해놓은 상태
> issue #49 : 선호 : group : 그룹 추가 기본 코드 및 쿼리 생성

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #44 
> 
<br/>
* 회원 탈퇴 기능을 넣었습니다. 
* 그리고 지난번 회의때 말했던 dao에 있는 public을 지웠습니다. 
<br/>
*
> #44 : 김혜원 : 회원 탈퇴 : 회원 탈퇴 기능 구현 테스트 완

- Backend/src/main/resources/SQL/DDL/joinedgroup_table.sql
* #74 joinedgroup ddl 추가
> 
<br/>
* #74 joinedgroup ddl 추가
<br/>
*
> #74 : 김혜원 : joinedgroup ddl : create table joinedgroup

- Backend/src/main/java/com/example/studyproject/codemn/CodeMn.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnController.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnDao.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnService.java
- Backend/src/main/resources/sqlMapper/codemn/codeMnMangae_SQL.xml
* 대분류 관리 기능 생성
> 
<br/>
* 기능추가
1. 추가 * 확인필요
2. 삭제 
3. 수정 
4. 조회
<br/>
* postman 에서 객체 전송 테스트 실패로 추가 기능 테스트 실패
* @RequestBody 로 받아오는 건 postman 전송 방식 확인 필요
> #84 : 이서연 : code_m : code_m 대분류 관리

- Backend/src/main/java/com/example/studyproject/joinedgroup/Joinedgroup.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/resources/SQL/DDL/joinedgroup_table.sql
- Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
* #80 그룹 가입 신청
> 
<br/>
* 그룹 가입 신청하는 로직을 구현했습니다.
* joinedgroup에 insert 하기 
<br/>
* sql에서 객체를 삽입할 때는 group_id.group_id와 같이 .을 이용하여 삽입합니다.
> #80 : 김혜원 : joinedgroup insert : 그룹 가입 신청

- Backend/src/main/java/com/example/studyproject/codemn/CodeMnController.java
* #92 
* 코드 신규추가 에러 수정
> 
<br/>
* 아이디 chk 메서드 삭제
* 해당 중복검사 메서드는 별개의 기능으로 구현 (#95 )
<br/>
*
> #92 : 이서연 : code_m : 코드 신규추가 에러 수정

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/email/EmailService.java
- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
- Backend/src/main/resources/application.properties
- 임의 번호 이메일 전송
* #91  
* 이메일 인증
> 
<br/>
* 이메일 인증 메일 발송 메서드 구현
* 인증번호 체크 메서드 구현
<br/>
* mailCheck 메서드에서 number 값 유지가 안되는데 이 값을 어디서 저장할지?
* 세션에서 저장할지, 컬럼에 저장할지,,,
https://1-7171771.tistory.com/141
> #91 : 이서연 : member : 이메일 인증

- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #100 
* 비밀번호 찾기 시 계정잠금 해제 및 실패횟수 초기화
> 
<br/>
* 비밀번호 찾기 성공 시 
* 계정잠금 해제
* 실패횟수 초기화
* sql 수정, service 수정
<br/>
*
> #100 : 이서연 : member : 비밀번호 찾기 시 계정잠금 해제

- Backend/src/main/resources/SQL/DDL/joinedgroup_table.sql
* #105  ddl create구문 수정
> 
<br/>
* 테스트 완료 후 올립니다.
<br/>
*
> #105 : 김혜원 : joinedgroup ddl update : joinedgroup create 구문 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #95 
> 
<br/>
* 중복됐던 메서드 활용해서 아이디 중복검사로 수정
<br/>
*
> issue #95 : 봉선호 : MemberController : 아이디 중복 검사 추가

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
* #97 
> 
<br/>
* 세션 해놨었는데 깜빡함.. 로거 추가해서 테스트 완료
<br/>
*
> issue #97 : 봉선호 : Member : 세션 추가

- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
* #107  가입 상태 변경
> 
<br/>
* 
json 보내는 형식 
```
{
"group_id" : {"group_id" : "1"},
"user_id" : { "user_id": "minhyun"},
"role" : "200",
"joinstatus" : "0",
"submission_cnt" : 0
}
```
<br/>
*
> #107 : 김혜원 : joinedgroup 가입 상태 변경 : 가입 상태 변경하기 update

- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
* #111  joinedgroup 가입 참여자, 그룹장 구분하는 로직 작성
> 
<br/>
* 그룹장이면 true를, 참여자면 false를 받아 구분하여 insert했습니다.
<br/>
*
> #111 : 김혜원 : joinedgroup 가입 구분 : joinedgroup 가입 참여자, 그룹장 구분하는 로직 작성

- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
Reverts seoyeonDev/Su-p#119
머지 취소
> Revert "issue #116 : 봉선호 : Group : 그룹 삭제 메서드 생성"

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnController.java
- Backend/src/main/java/com/example/studyproject/email/EmailService.java
- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/Joinedgroup.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/SQL/DDL/joinedgroup_table.sql
- Backend/src/main/resources/application.properties
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
Reverts seoyeonDev/Su-p#118
머지 취소
> Revert "issue #116: 봉선호 : Group : 그룹 수정 충돌 테스트 & 수정 메서드 생성 커밋"

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #125 
> 
<br/>
* 멤버 세션 추가 및 체크 복구
* 그룹 수정 메서드 복구
* 그룹 삭제 메서드 복구
<br/>
*
> issue #125 : 봉선호 : Member, StudyGroup : 멤버 세션, 그룹 삭제 메서드 복구

- .github/ISSUE_TEMPLATE/feature_request.md
* label 명 변경으로 해당 내용 추가
todo > feature
> 
<br/>
*
<br/>
*
> feature PR template 변경

- Backend/src/main/resources/SQL/DATA/studygroup_data.sql
- Backend/src/main/resources/SQL/DDL/studygroup_table.sql
* #121 studygroup table 생성 및 data를 추가했습니다. 
> 
<br/>
* 14개의 행을 추가하였습니다. 
<br/>
*
> #121 : 김혜원 : studygroup ddl 및 data : studygroup ddl 및 data 추가

- Backend/src/main/resources/SQL/DATA/joinedgroup_data.sql
* #122  joinedgroup 데이터를 추가했습니다.
> 
<br/>
* member와 studtgroup 데이터가 있어야 삽입 가능합니다.
<br/>
*
> #122 : 김혜원 : joinedgroup data : joinedgroup 데이터 추가

- Backend/src/main/java/com/example/studyproject/codemn/CodeD.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeM.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnController.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnDao.java
- Backend/src/main/java/com/example/studyproject/codemn/CodeMnService.java
- Backend/src/main/resources/sqlMapper/codemn/codeMnMangae_SQL.xml
* #94 
> 
<br/>
* 신규추가
* 수정
* 조회
* 삭제
* 신규 입력 시 기존 코드 조회
<br/>
*
> #94 : 이서연 : code_d : 세부 코드 기능 추가

- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogs.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
- Backend/src/main/resources/SQL/DATA/studylogs_data.sql
- Backend/src/main/resources/SQL/DDL/studylogs_table.sql
- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #139 
* #140 
> 
<br/>
* DDL, Data 생성
* xml, dao, service, controller 생성
<br/>
*
> #140 : 이서연 : studylogs : studylogs 초기세팅

- Backend/src/main/resources/SQL/DATA/code_data.sql
* #143 
> 
<br/>
* code_data.sql 파일 생성 
* AUTH 코드 데이터 업로드
<br/>
*
> #143 : 이서연 : code_d : AUTH 코드 데이터 업로드

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #138 
> 
<br/>
* 그룹상태변경 메서드 및 스케줄러 생성
* 코드정렬 실행
<br/>
* 그룹상태변경 시 date 외 joinedgroup 멤버 조건 자세히 확인필요
* - StudyGroupManage_SQL.xml 파일에서 selectListStudyGroup, createGroup 에러 발생하여 주석처리 @Ohnus
> #138 : 이서연 : Studygroup : 그룹상태변경 메서드 및 스케줄러

- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #146 
> 
<br/>
* 쿼리 설명 추가
<br/>
*
> issue#146 : 봉선호 : studygroup : selectListStudyGroup 쿼리 설명 추가

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #147 
> 
<br/>
* result type을 list에서 hashmap으로 수정
<br/>
* 컨트롤러 createGroup(그룹생성) 메서드의 그룹id 생성하는 부분에서 자릿수를 잘못 지정해놔서 수정함
* 원래는 버그로 이슈 생성해서 하려 했으나 147번 이슈 고치면서 같이 테스트하다가 모르고 커밋해버림
> issue#147 : 봉선호 : studygroup : resulttype 수정

- Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/SQL/DDL/penaltylog_table.sql
- Backend/src/main/resources/sqlMapper/penaltylog/StudyGroupManage_SQL.xml
* #157 
> 
<br/>
* 패널티 로그 ddl 생성
* 패널티 로그 java class 파일 생성
<br/>
*
> issue#157 : 봉선호 : penaltylog : 패널티 로그 ddl, class 파일 세팅

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #151 
> 
<br/>
* 그룹 상세조회 + 조회수 자동 +1 증가
<br/>
*
> issue#151 : 봉선호 : studygroup : 그룹 상세조회 + 조회수 자동 카운트

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #152 
> 
<br/>
* 제목으로 그룹 리스트 검색하기
* like로 검색
<br/>
*
> issue#152 : 봉선호 : studygroup : 그룹 제목으로 검색

- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogs.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
- Backend/src/main/resources/SQL/DATA/studylogs_data.sql
- Backend/src/main/resources/SQL/DDL/studylogs_table.sql
- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #141 
> 
<br/>
* 신규추가 메서드 추가
* post_id 를 group_id 에 따라 SEQUENce 를 적용하여 테이블 pk 값 추가
<br/>
* 초기세팅 DDL 및 java 초기세팅이 필요하여 #139 해당 브랜치에서 새로운 브랜치를 파생함.
> #141 : 이서연 : studylogs : 결과물 신규추가 및 테이블 DDL 수정

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
* #177 
> 
<br/>
* 충돌난 부분 수정하면서 머지하다가 중괄호 하나 빠짐
* 추가해서 수정
<br/>
*
> issue#151 : 봉선호 : studygroup : 조회수 업데이트 중괄호 하나 빠진 부분 고침

- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
* #170 
> 
<br/>
* dao class -> interface로 변경
<br/>
*
> issue#170 : 봉선호 : penaltylog : dao class -> interface로 변경

- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #166 
> 
<br/>
* 목록 전체조회 추가
<br/>
*
> #166 : 이서연 : studylogs : 목록 전체조회

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
- Backend/src/main/resources/application.properties
* #165 
> 
<br/>
* redis dependency 오류로 우선 SEssion 구현
* Dependency 'org.springframework.boot:spring-boot-starter-data-redis:2.2.1.RELEASE' not found 오류인데 실존하는 버전임 -> 다른 버전으로 변경해도 발생/ 스프링 버전이 안맞나 했는데 3.0.x 이상이면 맞는다고 함. 우리 3.2.3인걸로 알고있음
<br/>
https://keeeeeepgoing.tistory.com/15
https://herojoon-dev.tistory.com/170
> #165 : 이서연 : member : email 인증번호 등록구현

- Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
* #190 
> 
<br/>
* 생성자, getter, setter, tostring 수동생성한 것들 주석처리함
<br/>
*
> issue#190 : 봉선호 : vo : 페널티로그, 스터디그룹 vo 수동 생성 주석처리

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Frontend/src/pages/studygroup/StudyList.js
* #192 
> 
<br/>
* 프론트단 초기 세팅 작업하면서 그룹 리스트 호출하는 메서드의 리턴을 List로 수정했었는데 커밋을 깜빡해서 추가 커밋
<br/>
*
> issue#192 : 봉선호 : studygroup : 프론트단 초기세팅에 따라 그룹 리스트 호출 메서드 리턴 변경

- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #206 
> 
<br/>
* StudyLogs_SQL.xml 에러 수정
<br/>
*
> issue#206 : 봉선호 : studylogs : StudyLogs_SQL.xml 에러 수정

- Frontend/src/pages/member/Join.js
* #194 member id 중복 체크 및 비밀번호 일치 여부 확인
> 
<br/>
* 클래스로 선언되어있던 구조를 함수의 구조로 (더 권장하는 방법) 바꿔서 아이디 중복 체크와 비밀번호 일치 여부를 진행했습니다.
* 
<br/>
*
> #194 : 김혜원 : member join : member id 중복 체크 및 비밀번호 일치 여부 확인

- Backend/pom.xml
- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
- Backend/src/main/java/com/example/studyproject/email/RedisConfig.java
* #199
> 
<br/>
* redis 설치
* redis Template 설정
* redis 인증번호 저장 및 호출
<br/>
* 백그라운드에서 redis 설치 및 실행 후 동작합니다.
* [맥 버전 설치방법 ](https://herojoon-dev.tistory.com/170)
* 결과
> #199 : 이서연 : member/redis : redis 연결

- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycle.java
- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleDao.java
- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleService.java
- Backend/src/main/resources/SQL/DDL/assigncycle_table.sql
- Backend/src/main/resources/sqlMapper/assigncycle/AssignCycleManage_SQL.xml
* #201 
> 
<br/>
* 회차 테이블 생성
* BE 기초 세팅
* 서비스: 회차 계산 메서드 생성
* mapper: 회차 insert 쿼리 수정
<br/>
*  ![image](https://github.com/seoyeonDev/Su-p/assets/88930889/a3a91733-558e-40b2-a43f-cb626c60b669)
* 위와 같은 형태로 리스트를 파라미터로 불러오면 String 형식으로 불러오게 됨
* 일단 임의 조치로 테이블, vo 모두 String형식으로 해놓고 테스트 완료
> issue#201 : 봉선호 : studygroup : assigncylce 테이블 생성

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
* #202 
> 
<br/>
* 그룹 생성 시 회차 테이블에 아이디, 시작날짜, 종료날짜, 회차 데이터 삽입
* 과제 총 제출 횟수 계산식 컨트롤러에서 서비스로 넘김(생성, 수정 메서드)
<br/>
* ![image](https://github.com/seoyeonDev/Su-p/assets/88930889/bb16c607-3fde-40b7-99e8-125e94ceec9f)
* 컨트롤러에 있던 과제 제출 횟수 계산식 서비스단으로 넘겼습니다.
* 월단위 계산할 때는 ChronoUnit.MONTHS.between(startDate, endDate);로 했었는데 30일 기준잡고 연도차이도 고려할거면 ChronoUnit.DAYS.between(startDate, endDate); 사용하는게 나을 거 같아서 수정했습니다.
> issue#202 : 봉선호 : studygroup : 그룹 생성 시 회차 데이터 생성, 생성 및 수정 메서드 보완

- Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
> issue219 : 이서연 : joinedgroup : 에러 수정

- Frontend/src/pages/member/Join.js
* #217 
> 
<br/>
* 회원가입 구현 
* 
- 아이디 유효한지 체크
- 아이디 중복 체크
- 비밀번호 영어, 숫자, 특수문자 포함 검사
- 비밀번호 일치 여부 확인
- 닉네임 중복검사
- 이메일 인증 
- 회원약관 동의 후 회원가입 진행
<br/>
* 파일 전송하는 부분 구현해야 함
> #217 : 김혜원 : member 회원가입 : 회원가입 구현

- Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/SQL/DDL/penaltylog_table.sql
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #223 패널티 조회
<br/>
* userId별로 조회, groupId별로 조회
* 
<br/>
원래 Timestamp였던 penaltydate를 삭제한 후, 
int인 penalty_round로 수정하였습니다.
개인 DB에 반영해주세요. 
```
-- 회차로 변경
ALTER TABLE public.penaltylog
DROP COLUMN penaltydate;
ALTER TABLE public.penaltylog
ADD COLUMN penalty_round int NOT NULL;
```
이에 맞춰 vo도
```
private String user_id;
private String group_id;
private String title;
private String logcontent;
private int penalty_round;
``` 
로 수정하였습니다. getter, setter 쓰는 분은 한 번 확인 해주세요!
> #223 : 김혜원 : penalty 조회 : penalty userId, groupId 별로 조회 기능

- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #225 penalty 삭제 
<br/>
* 
user_id, group_id, penalty_round로 삭제를 진행하였습니다. 
<br/>
*
> #225 : 김혜원 : penalty 삭제 : penalty userId, groupId, penalty_round로 삭제하기

- Frontend/src/pages/member/Login.js
- Frontend/src/pages/member/mypage/Info.js
* #226 
<br/>
* FE: 로그인 후 서버단에서 받은 아이디로 유저 정보 읽고 페이지에 뿌려주기
* FE: 사진 연결(멤버에 사진 불러오는 메서드 없어서 스터디로그 메서드로 임시 테스트 완료)
* FE: 버튼 클릭에 따른 입력칸 활성화 및 비활성화
<br/>
*
> #226 : 봉선호 : member : 로그인 로직 일부 수정, 마이페이지로 정보 불러오기 등

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #231 
<br/>
* BE: 로그인 후 아이디와 결과 메시지 클라이언트단으로 보내도록 리턴 로직 수정
* BE: 아이디로 유저의 일부 정보 조회하는 메서드 추가
<br/>
*
> issue#231 : 봉선호 : member : 로그인 로직 일부 수정, 마이페이지로 정보 불러오기 등

- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleService.java
* #221 
<br/>
* 서비스단에 withHour, withMinute으로 시간 설정해서 해결
<br/>
*
> issue#221 : 봉선호 : assgincycle : 11시59분 추가

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
* #249 
<br/>
* CORS 어노테이션 삭제
<br/>
*
> issue#249 : 봉선호 : MEMBER : CORS 어노테이션 삭제

- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #240 충돌 병합시 </select> 누락 
<br/>
*
<br/>
*
> #240 : 김혜원 : penalty bug : penalty xml 누락된 부분 처리

- Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/SQL/DDL/penaltylog_table.sql
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #236  penalty insert 및 컬럼 수정
* #237  기존 패널티 조회 
<br/>
* penalty insert 기능을 구현하였고, 
* 저번 회의 때 테이블 컬럼을 변경하였는데 이에 맞게 컬럼을 수정하였습니다. 
* 그리고 기존 패널티 조회 할 때 log_count를 long으로 반환하였기 때문에 이에 맞춰 vo도 long으로 수정하였습니다. 
<br/>
* ```alter table penaltylog drop column title;``` 
위 문구를 실행해주세요
> #236 : 김혜원 : penalty insert : penalty insert 및 컬럼 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberDao.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
* #197 member 주석 정리
<br/>
* member 주석 정리
<br/>
*
> #197 : 김혜원 : member 주석 : member 주석 정리

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/resources/application.properties
- Frontend/src/pages/member/Join.js
* #238  멤버 회원가입 파일 업로드 기능 
<br/>
* 
원래 코드 
```
@PostMapping("/join")
public void join(@RequestBody Member vo, MultipartFile f) throws NoSuchAlgorithmException {
```
<br/>
변경 후 코드 
```
@PostMapping("/join")
public void join(@RequestPart("vo") Member vo, @RequestParam(value="file", required=false) MultipartFile f) throws NoSuchAlgorithmException {
```
@RequestBody를 사용하면 JSON과 파일을 동시에 받을 수 없습니다. 
대신 @RequestPart를 사용하여 multipart 요청의 각 부분을 처리해야 합니다.
그래서 vo는 @RequestPart로 받았고, 파일은 @RequestParam으로 받아서 처리를 하였습니다. 
<br/><br/><br/>
**react** 
<br/>
```
const data = {
"user_id": userId,
"password": password,
"name": name,
"nickname": nickname,
"email": email,
"join_date": null, …
```
> #238 : 김혜원 : member 회원가입 파일 업로드 : member 회원가입 파일 업로드

- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
* #234 
<br/>
* Redis  시간 제한 추가
<br/>
*
> issue234 : 이서연 : member : redis 시간제한 추가

- Frontend/src/pages/member/Login.js
- login Function 연결 및 오류처리 로직 추가
* #235 
<br/>
* CORS 에러 발생 > localhost:3000 으로 변경해주니 해결
<br/>
*
> #235 : member : login FE

- Frontend/src/pages/member/FindId.js
- 아이디찾기 기본 페이지 구현
* #257 
<br/>
* 아이디찾기 페이지 구현
<br/>
* 아이디찾기 페이지의 이메일 인증 구현 필요
> #257 : member : login FE

- Frontend/src/styles/components/Common.css
* #265 공통 css 디자인 작성
<br/>
* 피그마 UI 작성한 것을 참고하여 input type="text" type="password"와 button을 디자인 했습니다.
<br/>
*
> #265 : 김혜원 : common css : 공통 css design 만들기 button, input

- Backend/src/main/java/com/example/studyproject/files/Files.java
- Backend/src/main/java/com/example/studyproject/files/FilesDao.java
- Backend/src/main/java/com/example/studyproject/files/FilesService.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/resources/SQL/DDL/files.sql
- Backend/src/main/resources/sqlMapper/files/FilesManage_SQL.xml
* #258 
<br/>
* 파일 테이블 및 클래스 파일 생성
* 멤버 회원가입 시 이미지 정보 파일 테이블에 추가하는 기능도 해당 이슈에서 해결함(파일 클래스 있어야 가능해서)
<br/>
* 회원 정보 수정 시 파일 테이블 업데이트 해야 하는데 다른 이슈에서 수정 부분을 많이 건드려서 이번 주 pr 후 작업하겠음
* 스터디로그 파일 테이블 추가는 혜원 파트 작업 후 해야 될 거 같음
> issue#258 : 봉선호 : files : 파일 테이블 및 클래스 파일 생성

- Frontend/src/pages/member/mypage/ChangePwd.js
* #259 
<br/>
* FE 비밀번호 정규화
<br/>
*
> issue#259 : 봉선호 : member : FE 비밀번호 정규화

- Frontend/src/pages/member/Join.js
* #254 이메일 10분 카운트
<br/>
* 메일 수신에 성공하면 10분 카운트를 진행하였습니다. 
* 이미지를 선택할 때 미리보기로 보이게 만들었습니다.
<br/>
*
> #254 : 김혜원 : member 회원가입 10분 안내 : member 회원가입 이메일 10분 안내 및 이미지 미리보기

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/member/MemberService.java
- Frontend/src/pages/member/Login.js
* #256 
<br/>
* - localStorage FE
* - loginID service 반환 BE
<br/>
* member LOGIN 전체 로직 수정 필요해 보임. Controller에서 전송 시와 loginService 호출 내용이 일치하는지 확인 필요. 결과가 unlocked 여도 service에서 else 로 로직이동
> #256 : member : login FE & BE

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
* #256 
<br/>
* Controller msg 에러 해결
<br/>
* 해당 안내 msg 가 unlocked 로 초기화되어 잘못된 비밀번호 작성
> issue256 : 이서연 : member : Controller 메세지 에러 해결

- Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
- Frontend/src/pages/member/FindId.js
* #279 
* - 이메일 인증
* - 10분 제한시간 구현
* - BE의 number 반환 제거
<br/>
* 이메일 인증 : emailSend & emailChk 
* 시간제한 : timer 관련 
* response.data 반환 시 인증번호 (number) 이 전부 노출되어 mailSend 반환값에 number 제거
<br/>
* mailSend number 반환값 제거시 영향도 체크 요청
> #279 : member :이메일인증 / 시간제한

- Frontend/src/App.js
- Frontend/src/pages/studylogs/StudyLogs.js
* #280 
<br/>
* insert 기본 틀 생성
* insert 기본기능 생성
<br/>
* group_id 가 없어 임의로 지정
* 기본 제목, 내용만 넘김
> #280 : studylogs : insert FE

- Backend/src/main/resources/SQL/DDL/studylogs_table.sql
- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #272 
<br/>
* 스터디로그 테이블 ddl 수정(pk 2개 지정)
<br/>
*
> issue273 : 봉선호 : studylogs : 스터디로그 테이블 ddl 수정

- Frontend/src/pages/member/mypage/Info.js
* #275 
<br/>
* FE 마이페이지 정보수정 이메일 인증시간 추가(혜원 코드 참조)
<br/>
*
> issue275 : 봉선호 : member : FE 마이페이지 정보수정 이메일 인증시간 추가

- Frontend/src/App.js
- Frontend/src/pages/studygroup/CreateStudygroup.js
* #284 studygroup insert 틀 만들기
<br/>
*  #284 studygroup insert 틀 만들기
<br/>
* 
```
const [formData, setFormData] = useState({
group_id: '',
leader_id: '',      // 로그인 한 아이디 넣기
title: '',          // 스터디제목
name: '',           // 스터디명
study_desc: '',
kind: '',           //아직 구현 미정
status: '',
mem_cnt: 0,
startdate: '',      // 활성화 상태
enddate: '',
view_cnt: 0,        // 조회수 
chk_m: '',          // 제출 기준
chk_min_cnt: 0,     // 제출최소횟수
chk_total_cnt: 0,   // 전체제출횟수
penalty: 0,         // 패널티 기준
});```
이렇게 하나의 const안에 객체처럼 여러개를 작성할 수 있습니다.
> #284 : 김혜원 : studygroup 생성틀 만들기 : studygroup 생성틀 만들기

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/src/App.js
- Frontend/src/components/Header.js
- Frontend/src/pages/member/mypage/InputPassword.js
* #277 
<br/>
* BE, FE 마이페이지 접속 위한 비밀번호 검증 페이지 추가
<br/>
*
> issue275 : 봉선호 : member : BE, FE 마이페이지 접속 위한 비밀번호 검증 페이지 추가

- Frontend/src/components/Header.js
* #292 
<br/>
* localStorage를 전역변수에 담아 적용하려고 했는데, localStorage.remove를 할 경우 전역변수 버전 관리가 어려워 생략 (이에 대한 논의 필요)
* 변경을 감지하는 함수를 통해 가져오거나 (mypage 같은 Header.js를 제외한 외부 컴포넌트에서는 어떻게 작동할지 모르겠음), 그대로 localStorage 전체 문법을 사용하여 가져오기.
* 현재 코드에서는 localStorage의 user_id 가 정상적으로 삭제되었는지 확인하기 위해 alert 3번 사용하여 코드가 지저분해 보임.
<br/>
* #291 
* localStorage 와 session : session은 보안이 더 중요한 경우, localStorage는 속도가 더 중요한 경우 사용한다. 이전에 localStorage 에서 user_id를 담는 정도는 보안적으로 문제의 소지가 적다고 확인했기 때문에 localStorage 사용.
* 뿐만 아니라, session에 담아서 이를 가져오려면 BackEnd의 전면 수정이 필요하기 때문에 효율적인 측면에서도 localStorage 사용
> #292 : member : logout FE

- Frontend/src/pages/member/Join.js
* #289 member 이메일 인증 검사 수정
<br/>
*member 이메일 인증 검사 수정 
이메일 인증 번호 검사를 처음엔 return number로 확인하였으나, get 요청으로 수정 
<br/>
*
> #289 : 김혜원 : member 이메일 인증 검사 수정 : member 이메일 인증 검사 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/components/Header.js
- Frontend/src/pages/joinedgroup/JoinedList.js
- Frontend/src/pages/member/Login.js
* #304 
<br/>
* react-cookies 설치
* cookie 사용 (그런데 response data 에서 cookie 를 받아오는건 실패했고, userId 값을 입력하는데 withCredentials 을 사용하지 않고 react - cookies 를 사용해도 되는거 아닌지? / 완전히 이해 못함 ㅜㅜ 너무 어렵고 방법이 많다)
<br/>
*
> #304 : member cookies : login & logout

- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleDao.java
- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleService.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/resources/sqlMapper/assigncycle/AssignCycleManage_SQL.xml
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
- Frontend/src/App.js
- Frontend/src/pages/studygroup/UpdateStudygroup.js
- Frontend/src/routes/Home.js
* #300 
<br/>
* FE: 현재 그룹 상세 조회 페이지가 없어서 우선 Home.js에 수정 링크 걸어서 페이지 구현함
* 상세페이지에서 수정하기 버튼 누를 때 그룹 참여 인원 체크하므로 수정페이지에선 제약 안걸음
* 추후에 상세페이지에서 수정하기 버튼 눌러서 수정페이지로 갈 때 그룹id 가져가서 정보 불러와서 뿌려줘야 함
* 현재는 임의로 그룹id 하드코딩해서 테스트한 상태
* BE: 수정 정보 받아서 그룹 정보 수정
* 날짜, 제출횟수는 그룹 생성 로직과 비슷
* assigncycle 테이블에서 그룹id로 기존 정보 삭제 후 새로 추가하는 방식으로 구현함
<br/>
*
> issue#293 : 봉선호 : studygroup : 그룹 수정 기능 구현

- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #301 
<br/>
* BE: 삭제 기능도 그룹 상세페이지 없어서 기능만 수정함
* 기존 스터디그룹 테이블에서만 삭제 => studygroup, joinedgroup, assigncycle에서 해당 그룹id 관련 정보 모두 삭제로 변경
* 상세페이지로 넘어갈 때 joinedgroup 조회해서 사이즈 체크 후 사이즈를 클라이언트단으로 넘겨서 수정이나 삭제 때 이용하는게 좋을 듯
* 추후에 상세페이지 만들게 되면 joinedgroup 사이즈 1 이하일 때만 수정, 삭제 가능하도록 버튼 구현하면 될 듯 함
<br/>
*
> issue#301 : 봉선호 : studygroup : 그룹 삭제 기능 업데이트

- Frontend/src/components/Header.js
- Frontend/src/routes/Home.js
- Frontend/src/styles/components/Common.css
* #307  content 중앙 배치 
<br/>
*
<br/>
```
return (
<div className='common-content-container'>
<div className='common-content'>
{ /*  여기에 본문 내용 작성하는 html 넣기 */ }
</div>
</div>
);
```
이런식으로 className을 반영해서 사용하면 됩니다. 
<br/>
*
> #307 : 김혜원 : common 공통 css 추가 : content 중앙 배치

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupDao.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
- Frontend/src/pages/studygroup/StudyList.js
- Frontend/src/styles/studygroup/StudyList.css
* #299 
<br/>studygroup 목록 조회
*① 전체 보기*
조회순, 날짜순 정렬 기능 넣었습니다.
날짜순은 enddate desc로 넣어놨습니다.
<br/><br/><br/>
*② 검색*
검색했을 때 결과입니다.
<br/><br/><br/>
*③ 공통 열 목록 정의*
```
<sql id="studyGroupColumns">
group_id,
leader_id,
title,
name,
study_desc,
kind,
status,
mem_cnt,
startdate,
enddate,
view_cnt,
chk_m,
chk_min_cnt,
chk_total_cnt,
penalty
</sql>
```
위와 같이 정의 하면
```
<select id="selectStudyGroup" resultType="com.example.studyproject.studygroup.StudyGroup">
SELECT
<include refid="studyGroupColumns"/>
FROM studygroup
WHERE 1=1
AND group_id = #{group_id};
</select>
```
위와 같이 include를 통해 사용할 수 있습니다. 
<br/>
*  자동 들여쓰기 단축키를 사용해서 제가 작성하지 않은 부분도 - + 로 …
> #299 : 김혜원 : studygroup 목록 조회 : studygroup 목록 조회 및 검색 및 조회순, 최신순 정렬

- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #311 studygroup 모집중, 진행중만 검색 가능하게
<br/>
*studygroup 모집중, 진행중만 검색 가능하게 변경하였습니다.
STAT10 : 모집중, STAT20 : 진행중
<br/>
*
> #311 : 김혜원 : studygroup 조회 조건 추가 : studygroup 모집중, 진행중만 검색 가능하게

- Frontend/src/App.js
- Frontend/src/pages/member/ChangePwd.js
- Frontend/src/pages/member/FindPwd.js
* #312 
<br/>
* 아이디, 이름, 이메일 입력
* -> 일치하는 유저 정보가 있다면 인증번호 발송
* -> 인증번호 일치하면 changepwd.js로 이동
* chsngepwd에서 새로운 비밀번호 설정 (추후, 로그인 중인 정보 가져와서 로그인 정보, pwd, newPwd 보내는 로직 만들어야 함)
<br/>
*
> #312 : 김혜원 : member 비밀번호 찾기 : member 비밀번호 (아이디, 이름, 이메일) 검사하기

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/util/MyServlet.java
- Backend/src/main/java/com/example/studyproject/util/WebConfig.java
- Frontend/src/pages/member/Login.js
* #318 
<br/>
* withCredentials & Intercepter 사용하여 기능 구현 완료.
* 인터셉터 로그아웃은 로그인 페이지에 구현함.
* 인터셉터를 공통 js 파일로 생성하여 모든 화면에서 Import 만으로 사용할 수 있도록 공통함수로 생성하는건 어떨지??
* withCredentials 를 파라메터에 같이 담아서 {memberVo, {withCredentials:true}} 등의 방식으로 보냈을 때 에러 발생 (memberVo 인식 불가) -> 확인필요
* cookies, session, localStorage 등 사용 흔적이 남아있어 코드정리 필요.
<br/>
*
> #318 : member : login & logout

- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
* #314 
<br/>
* 그룹 생성 시 STAT10 디폴트로 쿼리에 고정
<br/>
*
> issue #314 : 봉선호 : studygroup : 그룹 생성 시 STAT10 디폴트로 쿼리에 고정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/src/pages/member/ChangePwd.js
- Frontend/src/pages/member/FindPwd.js
- Frontend/src/styles/components/Common.css
* #321 비밀번호 변경 및 css 적용
<br/>
* 이메일 인증을 받을 때 id, name, mail을 먼저 검사하므로 비밀번호 변경 컨트롤러에 있는 밑 로직을 없애고, 바로 비밀번호 변경을 할 수 있게 변경하였습니다. 
* memberService.chkPwd(id, name, email)와 (memberService.isPasswordCorrect(id, currentPassword) && chk == 1)를 없앴습니다. 
<br/>
*
> #321 : 김혜원 : member 비밀번호 변경 : member 비밀번호 변경하기 및 css 적용 및 margin 추가

- Frontend/src/pages/mystudy/MyStudy.js
- Frontend/src/styles/studygroup/MyStudy.css
* #323 my study 틀 만들기 (전체 , 운영중, 참여중, 종료된 스터디 메뉴틀 만들기 )
<br/>
* 
<br/>
*
> #323 : 김혜원 : my study 틀 만들기 : my study 메뉴 틀 만들기

- Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/SQL/DDL/penaltylog_table.sql
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
- Frontend/src/pages/studygroup/CreateStudygroup.js
* #326 
<br/>
1. 매일 스케줄러 실행 (자정)
2. 이전 회차까지 올린 studylog 개수 확인 (자정 기준 2일전 주차 조회)
3. 기준과 비교
4. 기준 미달시 / 같은 그룹, 같은 아이디, 같은 회차에 penalty 있는지 확인
5. penalty 없으면 penalty insert 실행
- Studygroup 기준과 비교 후 미달 시 Penaltylog 추가
- penalty_round 컬럼과 sg_assigncycle assigncycle 컬럼 일치하도록 변경
- 기존 insertPenaltylog 로직 오류 수정 후 신규 생성 (@RequestBody 로 받을 수 있는 로직이 아니라 판단 -> , )
- 기존 insertPenaltylog 쿼리문 수정 
- PenaltyLog 유효성 검사 추가 (Penalty 중복 확인)
- chkPenalty 의 Service , Controller 재정리
- 기존 selectPenalty 오류 수정 (조인 오류, studylog에 등록되지 않은 멤버는 결과에 미조회되는 오류 수정)
- 패널티 > 패널티 상한선 (초과 시 강퇴 당하는 기준?)
- 스케줄러 추가 (매일 자정 실행)
<br/>
* 여러가지 케이스를 고려하고 로직을 작성하여 주세요 ,,,,
* 리뷰 시 로직 …
> #326 : 이서연 : penaltylog : 패널티 studygroup 기준과 비교, 스케줄러 실행

- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogController.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/java/com/example/studyproject/util/WebConfig.java
- Backend/src/main/resources/application.properties
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #343 
<br/>
* penaltylog, Controller Service 분리
* 기존코드 주석 제거
* penaltylog 삭제 기능 추가
* CORS 에러 해결
* 디버깅 설정 추가 (application.properties)
<br/>
*
> #343 : 이서연 : penaltylog : 패널티 삭제

- Backend/src/main/java/com/example/studyproject/files/SupFilesInfo.java
- Backend/src/main/java/com/example/studyproject/files/SupFilesService.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
- Backend/src/main/resources/sqlMapper/supfiles/SupFilesManage_SQL.xml
- Frontend/src/pages/studylogs/CreatePost.js
- Frontend/src/styles/studylogs/CreateStudylogs.css
* #355 
<br/>
<br/><br/><br/><br/><br/>
이 메서드에서 studylogs를 읽어올 때 파일도 읽어와야 해서 기능을 추가하였습니다.
<br/>
저장, 수정 메서드에 파일 저장하는 게 중복되어있는데 이건  추후 리팩토링 진행할 예정입니다. 
<br/>
파일을 삭제할 때 객체를 담은 배열로 보내기 위해서 dto를 하나 생성하였습니다. 
<br/>
file_seq와 file_id가 프라이머리키이므로 두 개 모두 일치할 시 삭제하는 로직으로 바꿨습니다.
<br/>
파일의 경로를 불러오기 위하여 추가 작업을 하였습니다.
<br/>
<br/>
```
Not allowed to load local resource: file:///C:/Users/4ckdn/IdeaProject
```
저장된 이미지를 img src하였는데 로컬에서 불러오면 에러가 뜨는 상황이 발생했습니다.
(리액트에서 못 불러오게 막고 있는 느낌) 
해결책으로 웹 서버를 설치하였습니다. 
**1. 웹서버 다운**
https://httpd.apache.org/download.cgi
저는 여기서 다운 받았습니다.
하지만 맥은 기본으로 설치가 되어있다고 합니다.
<br/><br/>
**2. 웹서버 실행**
<br/><br/>
**3-1. …
> #355 : 김혜원 : studylogs 글 생성 및 수정 : studylogs 글 생성 및 수정

- Backend/src/main/java/com/example/studyproject/enums/JoinStatus.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/Joinedgroup.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
* #358 
<br/>
* enum class를 추가하여 enum을 사용하였습니다. 
<br/>
1)
<br/><br/>
2)
테스트 안정적으로 돌아갑니다.
> #358 : 김혜원 : JoinStatus enum 추가 :  JoinStatus enum 추가

- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
* #370 
<br/>
* String 타입을 JoinStatus enum 타입으로 변환했습니다.
<br/>
*
> #370 : 김혜원 : Joinedgroup :  String 타입 JoinStatus enum 타입으로 변환

- Backend/src/main/java/com/example/studyproject/StudyProjectApplication.java
- Backend/src/main/resources/application-mac.properties
- Backend/src/main/resources/application-windows.properties
- Backend/src/main/resources/application.properties
* #372 
<br/>
* application 시작할 때 운영체제를 분리해서 각 운영체제에 맞는 속성을 사용하도록 구현하였다.
<br/>
```
#spring.servlet.multipart.location=/Users/username/Sup/
```
여기서 username을 본인에게 맞게 수정해주면 될 것 같다. 
한 번 확인해 봐야 한다!,,
> #372 : 김혜원 : properties : 운영체제에 맞는 설정 파일 분리 추가 (Windows, Mac)

- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
- Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #364 
<br/>
* 그룹별 전체 목록 조회
* 사용자별 전체 목록 조회
<br/>
* COALESE 적용하여, 각자 null 이어도 조회 가능합니다.
* ex) group_id 가 null 이고 user_id 가 sylee 일 경우 : 그룹 상관없이 sylee 의 모든 studylogs 조회 가능..
> #364 : 이서연 : studylogs : 그룹별, 사용자별 전체 목록 조회

- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleDao.java
- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleService.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/StudyAttendanceResult.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
- Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogService.java
- Backend/src/main/resources/sqlMapper/assigncycle/AssignCycleManage_SQL.xml
- Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #362 
<br/>
1. 전체 제출 횟수 구하기 (AssignCycle)
2. 패널티 횟수 구하기 
3. ((전체 - 패널티) / 전체) * 100 = 출석률
* 예시 ( 10 - 1 / 10 ) * 100 = 90 %
전체 출석률이라면, 해당 사용자가 가입한 StudygroupId 리스트를 가져와, 총 penalty 개수를 count해서 구함
<br/>
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
> #362 : 김혜원 : joinedgroup : 전체 출석율 및 특정 스터디에 관한 출석율 구하기

- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
* #382 
<br/>
* LEFT JOIN으로 바꿔 수정하였습니다.
<br/>
*
> #382 : 김혜원 : penaltylog : 특정 그룹에 대한 penaltylog를 조회하는 쿼리문 수정

- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
* #396 
<br/>
* MyStudyDetail의 getGroupInfo로 통합 조회 후 값 전달
<br/>
*
> #396 : MyStudyDetail : groupInfo 메서드 MyStudyDetail 로 이동

- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
- Frontend/src/pages/mystudy/detail/MyStudyAdminAfterOpen.js
- Frontend/src/pages/mystudy/detail/MyStudyAdminBeforeOpen.js
- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/styles/mystudy/detail/MyStudyAdminAfterOpen.css
* #410 
* #406 
<br/>
* 목록 불러오기 할 때 penaltylog가 없는 member는 조회되지 않아서, sql문을 수정하였습니다. 
<br/>
*
> #406/#410 : 김혜원 : mystudydetail : open 후 관리자 페이지 구현

- Frontend/src/pages/mystudy/detail/MyStudyDetailAllList.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyList.js
* #411 
<br/>
* group_id 파라미터 전달 수정시 누락되었습니다. 
<br/>
*
> #411 : 김혜원 : mystudydetail : 전체 글 안 보이는 버그 수정

- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleDao.java
- Backend/src/main/java/com/example/studyproject/assigncycle/AssignCycleService.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/resources/sqlMapper/assigncycle/AssignCycleManage_SQL.xml
- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyAttendance.js
* #407 
* #408 
<br/>
* 백엔드 개발, 
* 프론트엔드 개발
<br/>
* 출석여부 조회가 가능한데 프론트에서는 나타나지 않는 문제 해결 필요
> #407, #408 : MyStudyDetail : 나의 출석 조회

- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHeader.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
* #409 
<br/>
* 전체글보기, 나의글보기와 비슷하게 HOME에도 post 상세보기 기능을 만들었습니다.
* 탭에 글쓰기 버튼을 만들었습니다.
<br/>
*
> #409 : 김혜원 : mystudydetail : HOME studylogs 상세보기 및 글쓰기 버튼 추가

- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailGroupInfo.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHeader.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyAttendance.js
* #426 
<br/>
- GroupInfo에 groupInfo 넘기기
- MyList 위치 조정
- Header 의 content 지우기
- Home 의 주석 정리
- 각종 기능 테스트
<br/>
*
> #426 : MyStudyDetail : 정리

- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHeader.js
- Frontend/src/pages/studylogs/CreatePost.js
- Frontend/src/pages/studylogs/PostDetail.js
* #420 
* #421 
<br/>
* 글 등록시, 전체 글 보기로 이동 (usecase mystudy-create-post 참고) 
* 글 수정시, 상세보기로 이동 (usecase mystudy-postdetail-update 참고)
<br/>
*
> #420/#421 : 김혜원 : studylogs : 글 등록 및 수정 후 url 이동

- Frontend/src/pages/mystudy/detail/MyStudyAdminAfterOpen.js
* #423 
<br/>
* 관리자 : 리셋버튼 구현
* 패널티의 개수가 1 이상인 사용자에게만 리셋 버튼을 부여
<br/>
*
> #423 : 김혜원 : penaltylog : 관리자 패널티 리셋버튼 구현

- Backend/src/main/java/com/example/studyproject/enums/JoinStatus.java
- Backend/src/main/java/com/example/studyproject/enums/StudygroupStatus.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Frontend/src/pages/studygroup/StudygroupDetail.js
* #425 
<br/>
* 1,2,3등의 임의의 코드로 적어놓은 값을 공통코드에 있는 표준 코드 값으로 변경
* 전후 상황을 봤을 때 studygroup detail (FE)와 연결되어 있어서, detail 페이지도 같이 수정
<br/>
*
> #425 : 김혜원 : studygroup : status 표준 코드 값으로 변경

- Frontend/src/components/Header.js
- Frontend/src/pages/member/Login.js
- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailGroupInfo.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHeader.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyAttendance.js
* #376 
<br/>
- localStorage 에 유효시간(expireTime) 추가
<br/>
- 코드 리뷰 시 필터를 통해 #476 (376인데 잘못 적음) commit 만 확인해주면 됨.
- 유의 : localStorage 사용 시 함수로 user_id의 value 만 가져오는 과정 필요 (다른 곳에 아직 미적용)
- 재사용성이 높아 React Custom Hook 사용하는법 확인 예정
> #376 : Login : 로그인 유효시간 변경

- Frontend/src/components/Header.js
- Frontend/src/pages/Common.js
- Frontend/src/pages/member/Login.js
- Frontend/src/pages/mystudy/MyStudy.js
- Frontend/src/pages/mystudy/MyStudyList.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyAttendance.js
* #436 
<br/>
* 공통함수 페이지 생성
* 공통함수 적용
<사용법>
- getIdFromLocalStorage() 후 import 하면 된다.
<br/>
*
> #436 : All : LocalStorage 공통함수 적용

- Frontend/src/pages/mystudy/MyStudyList.js
* #378 
<br/>
* 조회된 그룹이 없을 경우 "조회된 그룹이 없습니다." 안내 메세지 출력
<br/>
*
> #378 : MyStudyList : 조회된 그룹이 없을 때 안내 메세지 출력

- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
* #427 
<br/>
* 스터디 상세 조회 시 출석오류 수정
* 변수 초기화 시점이 attendance 를 불러오고 난 이후여서 발생하는 문제로 보여, 변수 없이 바로 조회 값을 차트 계산값에 추가함.
<br/>
*
> #427 : MyStudyDetailHome : 스터디 상세 조회 시 출석율 오류 수정

- Backend/src/main/java/com/example/studyproject/joinedgroup/Joinedgroup.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
- Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Frontend/src/pages/studygroup/StudygroupDetail.js
* #439 
<br/>
* 가입 및 취소 버튼 기능 구현
* Back) Joinedgroup의 role도 enum으로 변경 
<br/>
*
> #439 : 김혜원 : studygroup : 가입 및 취소 버튼 기능 구현

- Frontend/src/pages/mystudy/MyStudyList.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailAllList.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailHome.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyAttendance.js
- Frontend/src/pages/mystudy/detail/MyStudyDetailMyList.js
* #417 
* #442 
<br/>
* ① Each child in a list should have a unique "key" prop.
키 설정은 잘 되어있었지만, 위 warning이 떴다.
`<div key={String(item.group_id)} className='study-card'>` key 부분은 String으로 타입을 변경해주니 Warning이 사라졌다.
원래는 없어도 잘 되어야 하는데, 무슨 원인 때문에 안 되는 건지 잘 모르겠다.
<br/>
* ② Warning: validateDOMNesting(...): `<p>` cannot appear as a descendant of `<p>`.
```
<p>
<div>example</div>
</p>
```
p로 div를 안을 수 없어서 발생한 경고였다.
```
<div>
<div>example</div>
</div>
```
로 변경하였다.
<br/>
* ③ Warning: Failed prop type: The prop user_id is marked as required in MyStudyDetailMyList, but its value is undefined.
MyStudyDetailMyList에서 user_id가 필수값으로 받게 설정이 되어있는데, undefined라 발생하는 경고.
필수값을 변경해주었다. 
<br/> …
> #417 : 김혜원 : mystudy : 개발자도구 Warnings 수정

- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
* #338 
<br/>
* INSERT 시 AUTH 설정
<br/>
*
> #338 : 이서연 : Member : 회원가입 시 AUTH 설정

- Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
* #374 
<br/>
* 사용하지 않는 insertLog 삭제
<br/>
*
> #374 : 이서연 : StudyLogs : insertLogs 삭제

- Frontend/src/pages/member/ChangePwd.js
- Frontend/src/pages/member/FindPwd.js
* #336 
<br/>
* email, name 값을 전달해 백으로 보내주었습니다.
<br/>
*
> #336 : 김혜원 : member : 비밀번호 변경시 필수 파라미터값 전달하기

- Frontend/src/pages/mystudy/MyStudyList.js
- Frontend/src/pages/mystudy/detail/MyStudyDetail.js
* #437 
* #417 
<br/>
* useEffect 중복을 제거
* 지난번에 `<div key={String(group_id)}></div>` 를 넣어줬는데 반영이 제대로 안 되어 있어서 다시 추가
<br/>
*
> #437 : 김혜원 : mystudydetail : useEffect 중복 제거

- Backend/src/main/java/com/example/studyproject/files/SupFilesDao.java
- Backend/src/main/java/com/example/studyproject/files/SupFilesService.java
- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
- Backend/src/main/resources/sqlMapper/supfiles/SupFilesManage_SQL.xml
- Frontend/src/components/Header.js
- Frontend/src/pages/mypage/Info.js
* #458 
* #479 
* #457 
<br/>
* supfiles 의 메서드가 Log, profile 구분없이 사용되고 있었음. > 프로필 사진은 supfiles 의 file_type 에 'profile' 저장하여 구분자로 사용하여 해결
* 프로필용 메서드 생성 
* 기존 사진 없을 시 경로 default 로 설정
* 파일 수정 시 경로 없을 경우 경로 생성
* profile 전용 파일 조회 메서f 생성
* MEmberCOntroller filsService 오타 수정
<br/>
* 이미 존재하는 코드 수정 시 사용되는 곳 확인 후, 영향도 체크하여 수정 필요
> #458, #457, #479 : 이서연 : Member : 마이페이지 사진 수정 시 발생하는 에러 여러건 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/src/pages/member/Join.js
* #451 
* #457 
* #453 
* #456 
<br/>
* 회원가입 사진 등록 시 미리보기 크기 설정
* 회원가입 시 사진 이외의 파일 등록 불가 설정
* pwdchk 메세지 두개로 나눔. 비밀번호 유효성 검사 , 비밀번호 일치여부 체크
* checkNickNm 메서드 조건문 오류 수정
<br/>
*
> #451, 457,453,456 : Member : 멤버 회원가입 관련 오류 수정

- Backend/src/main/resources/SQL/DDL/assigncycle_table.sql
* #327 
<br/>
* 테이블 group_id 컬럼 타입 변경 (char > varchar)
<br/>
* 테이블 타입에 따라 발생하는 공백이었음. 테이블 변경 필요.
alter table public.sg_assigncycle
alter column group_id type varchar(255) using group_id::varchar(255);
> #327 : 이서연 : assigncylce : char > varchar 테이블 타입 변경

- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
- Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
- Backend/src/main/resources/SQL/DATA/code_data.sql
- Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
- Frontend/src/pages/studygroup/StudyList.js
- Frontend/src/pages/studygroup/StudygroupDetail.js
- Frontend/src/routes/Home.js
* #419 
* #489 
* #490 
* #496 
* #487 
<br/>
* 미로그인 시 studygroup detail 에러 수정
* 메인 스터디 목록 시작일/종료일 추가
* 스터디 디테일 제출기준, 기준횟수 표시
* studydetail 스터디 시작일 지난 스터디임에도 가입/가입취소 가능
* home 화면 모집 마감일, 작성자, 조회수, 상태 여부 추가
<br/>
* code_data.sql 의 데이터 insert 필요
> #419, #489, #490, #496, #487 : main, studygroup : 스터디그룹, 메인 수정

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/components/Header.js
- Frontend/src/pages/Common.js
- Frontend/src/pages/member/FindId.js
- Frontend/src/pages/member/Join.js
- Frontend/src/pages/member/Login.js
* #514 
<br/>
* sweet alert 공통 함수를 구현하였습니다.
<br/>
*  현재 Header.js와 member 폴더에만 sweet alert를 적용하였으며, 향후 전체 수정할 계획입니다.
> #514 : 김혜원 : member : sweet alert 공통 함수 만들기

- Frontend/src/components/Header.js
- Frontend/src/pages/member/Login.js
* #509 
<br/>
* 로그아웃 시 BE sesion 만료를 설정하였고,
* 세션 유지 시간이 60분으로 설정되어있었는데 → 30분으로 바꾸었다.
* 자동로그아웃 이 BE session도 만료되게 설정해놓았다.
출처 : 기능테스트 member
<br/>
*
> #509 : 김혜원 : 로그아웃시 session 만료하기

- Backend/src/main/java/com/example/studyproject/member/MemberController.java
- Backend/src/main/java/com/example/studyproject/util/MvcConfiguration.java
- Frontend/src/pages/mypage/ChangePwd.js
- Frontend/src/pages/mypage/Info.js
* #505 
* #503 
* #481
<br/>
* 비밀번호 변경 안 됨 - password 값이 제대로 전달 되지 않아 값을 제대로 전달하여 오류를 해결하였다.
* 마이페이지에서 수정을 누르면 f 가 null이라는 오류가 떴다.
null체크 + 로직을 수정해서 해당 오류를 해결했다.
* 마이페이지에서 `기본 이미지로 변경`버튼을 누르면 기존 이미지를 삭제하는 기능을 구현하였다.
<br/><br/>
<hr/>
<br/>
1️⃣ `/member/getImage` 확인
[문제]
① **저장된** 사진은 정상적으로 불러와짐
② **기본 이미지**는 **404** 에러와 함께 제대로 불러와 지지 않았음 
[해결]
→ 찾아보니 `resources/` 에 있는 정적 파일을 외부에서 접근하려면 `MvcConfiguration 클래스`에서 설정을 추가해야 하는 거였다.
그래서 해당 클래스를 구현하여 기본 이미지를 가져올 수 있었다.
`InputStream inputStream = getClass().getClassLoader().getResourceAsStream(defaultImg);` 이렇게 정적 리소스를 불러올 수 있다.
<br/>
2️⃣  `/member/defaultImg` 추가
[문제] : `기본 이미지`가 있는 상태에서 `기존 이미지`로 변경하려 할 때 `기존 이미지`의 `src`가 없음
① …
> #505,503,481 : 김혜원 : member : 마이페이지 비밀번호 변경 및 마이페이지 정보 수정 오류 해결

- Frontend/src/pages/Common.js
- Frontend/src/pages/studygroup/CreateStudygroup.js
- Frontend/src/pages/studygroup/StudyList.js
- Frontend/src/pages/studygroup/UpdateStudygroup.js
* #520 
* #521 
* #525 
<br/>
* 해당 단어를 바꾼 후, sweet alert도 적용하였습니다.
<br/>
*
> #520, #521, #525 스터디 제목, 스터디 설명으로 변경 및 비회원일 시 생성 화면 접근 불가능 설정
